import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import InboxComponent from '../components/InboxComponent';
import { getAccessTokenFromLocal } from '../LocalStorage/accessToken';
import {
  deleteMessagesFromLocal,
  addMessagesToLocal,
} from '../LocalStorage/messagesStorage';

function Inbox() {
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    const b = async () => {
      const res = await fetch('http://localhost:5000/message/messages', {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${getAccessTokenFromLocal()[0]}`,
        },
      });
      const data = await res.json();
      if (data.success) {
        await deleteMessagesFromLocal();
        setMessages(data.data.reverse());
        await addMessagesToLocal(data.data);
      }
    };
    b();
  }, [setMessages]);

  return (
    <div>
      <Head>
        <title>Inbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InboxComponent {...{ messages }} />
    </div>
  );
}

export default Inbox;
