import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import HomeComponent from '../components/HomeComponent';
import { useRouter } from 'next/router';
import {
  getAccessTokenFromLocal,
  deleteAccessTokenFromLocal,
} from '../LocalStorage/accessToken';
import {
  getMessagesFromLocal,
  deleteMessagesFromLocal,
} from '../LocalStorage/messagesStorage';
import { deleteUserFromLocal } from '../LocalStorage/userStorage';

import jwt from 'jsonwebtoken';

function Home() {
  const [unread, setUnread] = useState('');
  const [isLogin, setIsLogin] = useState(false);
  const [messageLength, setMessageLength] = useState(0);

  const router = useRouter();

  useEffect(() => {
    router.prefetch('/inbox');
    router.prefetch('/login');
    router.prefetch('/register');

    const a = async () => {
      const data = getMessagesFromLocal()[0];
      if (data) {
        setMessageLength(data.length);
        let ur = 0;
        for (let i = 0; i < data.length; i++) {
          if (data[i].isRead == false) {
            ur += 1;
          }
        }
        setUnread(ur);
      }
    };

    if (getAccessTokenFromLocal()[0]) {
      jwt.verify(
        getAccessTokenFromLocal()[0],
        process.env.NEXT_PUBLIC_JSON_SECRET_KEY,
        (err, decoded) => {
          if (err) {
            setIsLogin(false);
            deleteAccessTokenFromLocal();
            deleteMessagesFromLocal();
            deleteUserFromLocal();
          } else {
            setIsLogin(true);
            a();
          }
        }
      );
    } else {
      setIsLogin(false);
    }
  }, [router]);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLogin ? (
        <HomeComponent
          {...{
            unread,
            messageLength,
            router,
          }}
        />
      ) : (
        <div className="h-[100vh] w-full flex justify-center items-center flex-col">
          <h1 className="font-semibold mb-10 text-lg">
            You are not logged in{' '}
          </h1>
          <div>
            <button
              className="bg-red-500 w-24 h-12 rounded-md shadow-xl font-semibold text-white mr-5 transition-all hover:scale-105"
              onClick={() => router.push('/login')}
            >
              Login
            </button>
            <button
              className="bg-red-500 w-24 h-12 rounded-md shadow-xl font-semibold text-white ml-5 transition-all hover:scale-105"
              onClick={() => router.push('/register')}
            >
              Register
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default Home;
