import React, { useEffect } from 'react';
import LoginComponent from '../components/loginComponent';
import Head from 'next/head';
import { useRouter } from 'next/router';

function Login() {
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState('');

  const router = useRouter();

  useEffect(() => {
    router.prefetch('/');
  }, [router]);

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginComponent {...{ email, setEmail, password, setPassword, router }} />
    </div>
  );
}

export default Login;
