import React, { useEffect } from 'react';
import RegisterComponent from '../components/registerComponent';
import Head from 'next/head';
import { useRouter } from 'next/router';

function Register() {
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState('');
  const [username, setUsername] = React.useState('');

  const router = useRouter();

  useEffect(() => {
    router.prefetch('/');
  }, [router]);

  return (
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterComponent
        {...{
          email,
          setEmail,
          password,
          setPassword,
          username,
          setUsername,
          router,
        }}
      />
    </div>
  );
}

export default Register;
